# 🚀 Despliegue automático a GitHub Pages
# Este workflow construye y despliega mi portfolio automáticamente

name: Deploy to GitHub Pages

on:
  # Se ejecuta en cada push a la rama principal
  push:
    branches: ["main"]

  # También permite ejecutarlo manualmente desde GitHub
  workflow_dispatch:

# Permisos necesarios para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

# Solo permite un despliegue a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: professional-react-portfolio/package-lock.json

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Instalar dependencias
        working-directory: ./professional-react-portfolio
        run: npm ci

      - name: Construir el proyecto
        working-directory: ./professional-react-portfolio
        run: npm run build

      - name: Subir artefactos para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./professional-react-portfolio/dist

  # Job de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
